name: darttubefix
description: A lightweight and powerful YouTube and YouTube Music content extraction library for Dart, translated and adapted from pytubefix.
version: 1.0.8
repository: https://github.com/MrTG-CodeBot/darttubefix
homepage: https://github.com/MrTG-CodeBot/darttubefix
issue_tracker: https://github.com/MrTG-CodeBot/darttubefix/issues
topics:
  - youtube
  - youtube-music
  - pytubefix
  - stream-extractor
  - video-downloader

false_secrets:
  - /lib/src/innertube.dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

